Add basic PVC to persist file uploads for Drupal
inviqa/harness-base-php pull request #158
Opened 2019-10-15 11:24 UTC by g-foster2

2019-10-16 14:22 UTC, sgrichards approved these changes
LGTM

2019-10-16 14:31 UTC, andytson-inviqa commented
A more generic solution I'd already started a few weeks ago https://github.com/inviqa/harness-base-php/pull/161

2019-10-17 07:59 UTC, andytson-inviqa requested changes
I'd like consideration for my approach rather than merging this only for mine to be merged as well

2019-10-17 08:51 UTC, g-foster2 commented
@andytson-inviqa  That's great in principle but I understand these are needed ASAP yesterday and there is no-one on project to make any changes as we are under pressure to get all the apps deploying to Mikko's environment (OLP-718).

2019-10-17 08:56 UTC, andytson-inviqa commented on src/drupal8/helm/app/templates/application/php-fpm/deployment.yaml
> +          mountPath: /app/docroot/sites/default/files
I assume needs to be mounted on the nginx container as well for web access?

2019-10-17 09:43 UTC, andytson-inviqa commented on src/drupal8/helm/app/templates/application/php-fpm/deployment.yaml
> +          mountPath: /app/docroot/sites/default/files
I've asked around, and generally nginx does need access. My PR can be used with for example the nfs-server-provisioner chart to provide a test ReadWriteMany volume

2019-10-17 09:51 UTC, g-foster2020 commented on src/drupal8/helm/app/templates/application/php-fpm/deployment.yaml
> +          mountPath: /app/docroot/sites/default/files
Thinking it through - we still have the client-level overrides so these changes are not time-dependent; suggest they are changed to general tickets with your comments on how to do it in the better way you have come up with.

2019-10-31 12:36 UTC, closed without merging