Add standard k8s/helm labels
inviqa/harness-base-php pull request #481
Opened 2020-10-30 17:12 UTC by andytson-inviqa

These can't be used for selectors yet though as:
a) deployment selectors are immutable, so would require deployments to be deleted
b) service selectors would get updated before there are pods with the labels in, causing partial downtime during a deployment

2020-11-25 15:12 UTC, kierenevans requested changes
Extra files that might need some additions (jenkins pvc was added after this PR was raised):
```
src/_base/helm/app/_twig/templates/service/varnish/configmap.yaml.twig
src/spryker/helm/app/templates/service/jenkins/pvc.yaml
```

Only "required" suggestion is `src/_base/helm/app/templates/application/cron/deployment.yaml`

2020-11-25 15:12 UTC, kierenevans commented on src/_base/helm/app/templates/application/cron/deployment.yaml
> +    app.kubernetes.io/component: console
```suggestion
    app.kubernetes.io/component: cron
```

2020-11-25 15:12 UTC, kierenevans commented on src/akeneo/helm/app/templates/application/akeneo-file-storage-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/akeneo/helm/app/templates/application/akeneo-file-storage-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/akeneo/helm/app/templates/application/akeneo-uploads-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/akeneo/helm/app/templates/application/akeneo-uploads-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/drupal8/helm/app/templates/application/drupal-files-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/drupal8/helm/app/templates/application/drupal-files-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/magento1/helm/app/templates/application/magento-media-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/magento1/helm/app/templates/application/magento-media-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/magento2/helm/app/templates/application/magento-export-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/magento2/helm/app/templates/application/magento-export-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/magento2/helm/app/templates/application/magento-media-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/magento2/helm/app/templates/application/magento-media-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/spryker/helm/app/templates/application/spryker-data-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-11-25 15:12 UTC, kierenevans commented on src/spryker/helm/app/templates/application/spryker-data-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
```suggestion
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
```

2020-12-08 09:17 UTC, andytson-inviqa commented on src/akeneo/helm/app/templates/application/akeneo-file-storage-pvc.yaml
> +    {{- include "chart.labels" $ | nindent 4 }}
it's not specific to the webapp as mounted on multiple services, ditto for the rest of the suggestions

2020-12-08 09:31 UTC, kierenevans approved these changes

2020-12-08 15:53 UTC, merged