Add Spryker 202108.0 support
inviqa/harness-base-php pull request #655
Opened 2022-01-03 13:05 UTC by hgajjar

Fixes #654 

- [x] resolve composer dependency issues
- [x] incorporate latest Spryker config changes into config_local.php file
- [ ] fix broken yves->zed communication (could be related to config update)
- [ ] check if behat sample test is working (as we have updated behat modules to resolve composer deps)
- [ ] add php8 support (could be added later in a separate MR, as they also support PHP 7.4)

2022-01-07 16:01 UTC, andytson-inviqa commented on src/spryker/harness.yml
> +    tag: '7.16.2'
not all spryker projects will work with elasticsearch 7, though there's 6.8.22, which I'm changing to in another PR.

Should we do spryker version check here?

2022-01-07 16:02 UTC, andytson-inviqa commented on src/spryker/harness.yml
> +    root_dir: = @('app.web_directory') ~ '/BackendGateway'
not in older spryker versions

2022-01-24 11:12 UTC, andytson-inviqa requested changes

2022-01-24 11:12 UTC, andytson-inviqa commented on src/spryker/harness.yml
> +    tag: "= @('spryker.demoshop-version') <= '202009.0'? '6.8.22' : '7.16.2'"
Since demoshop-version is hard coded, can we either:

1) update UPGRADE.md to mention projects should put their demoshop version in workspace.yml
2) (1) and copy the demoshop-version into workspace.yml on `ws create`
3) use auto-detection if demoshop-version not supplied, with it not being supplied by default (harness can still reference another variable for ws create)

2022-01-24 11:18 UTC, andytson-inviqa commented on src/spryker/harness.yml
> +    tag: "= @('spryker.demoshop-version') <= '202009.0'? '6.8.22' : '7.16.2'"
also upgrading ES to the latest version
```suggestion
    tag: "= @('spryker.demoshop-version') <= '202009.0'? '6.8.23' : '7.16.3'"
```

2022-01-27 05:01 UTC, hgajjar commented
@andytson-inviqa I have worked on the changes you requested, could you please review it again?

2022-01-28 12:45 UTC, andytson-inviqa requested changes

2022-01-28 12:45 UTC, andytson-inviqa commented on src/spryker/harness.yml
> +    tag: "= @('spryker.demoshop-version') <= '202009.0'? '6.8.23' : '7.16.3'"
```suggestion
    tag: "= version_compare(@('spryker.demoshop-version'), '202009.0', '<=') ? '6.8.23' : '7.16.3'"
```

version_compare is less likely to have issues

2022-01-28 12:45 UTC, andytson-inviqa commented on UPGRADE.md
> +In order to make sure your project uses the right version of Elasticsearch and Zed root directory, make sure you set the
```suggestion

In order to make sure your project uses the right version of Elasticsearch and Zed root directory, make sure you set the 
```

2022-01-28 12:48 UTC, andytson-inviqa approved these changes, later dismissed

2022-01-28 13:27 UTC, andytson-inviqa approved these changes

2022-01-28 15:44 UTC, merged