Ignore null template key values
inviqa/harness-base-php pull request #679
Opened 2022-04-21 09:59 UTC by jbarton123

Currently for values set to `~` that are compiled together using this function, these values are still appended to the output. This ensures that for any null values passed into this function, that they are ignored.

2022-04-21 10:34 UTC, andytson-inviqa commented on src/_base/harness/config/functions.yml
> +    if (!$value) {
```suggestion
    if ($value===null) {
```

2022-04-21 10:35 UTC, andytson-inviqa commented on src/_base/harness/config/functions.yml
> +    if (!$value) {
'0' is a valid string but !$value is true for it

2022-04-21 12:32 UTC, hgajjar approved these changes

2022-04-28 11:18 UTC, andytson-inviqa requested changes

2022-04-28 11:18 UTC, andytson-inviqa commented on src/spryker/docker/image/nginx/root/etc/nginx/conf.d/zed.conf.template.twig
> +{% endif %}
misses zed api further down, however there's another PR for that https://github.com/inviqa/harness-base-php/pull/685

2022-04-28 13:22 UTC, andytson-inviqa commented on src/_base/_twig/docker-compose.yml/service/nginx.yml.twig
> +{% set hostnames = hostnames|merge(@('hostname_aliases')| filter(v => v is not empty) | map(alias => "#{alias}." ~ @('domain'))) %}
Just this bit now that is what we want to keep after @Chemaclass's PRs now merged

2022-04-28 13:23 UTC, andytson-inviqa commented on src/_base/_twig/docker-compose.yml/service/nginx.yml.twig
> +{% set hostnames = hostnames|merge(@('hostname_aliases')| filter(v => v is not empty) | map(alias => "#{alias}." ~ @('domain'))) %}
although should also be done for varnish. I'll create a PR

2022-04-28 13:36 UTC, Chemaclass commented on src/_base/harness/config/functions.yml
> +    }
Already done: https://github.com/inviqa/harness-base-php/pull/686

2022-04-28 13:47 UTC, andytson-inviqa commented on src/_base/_twig/docker-compose.yml/service/nginx.yml.twig
> +{% set hostnames = hostnames|merge(@('hostname_aliases')| filter(v => v is not empty) | map(alias => "#{alias}." ~ @('domain'))) %}
https://github.com/inviqa/harness-base-php/pull/689, I've instead done at the source

2022-04-28 14:16 UTC, closed without merging