Use develop version of php compatibility check tool, for 8.0 and 8.1 checks
inviqa/harness-base-php pull request #715
Opened 2022-06-03 12:32 UTC by kierenevans

Ref: https://github.com/PHPCompatibility/PHPCompatibility/issues/1312

The last release was in 2019 for php 7.4.

2022-09-12 08:29 UTC, andytson-inviqa commented on src/akeneo/application/skeleton/composer.json.twig
> +  "minimum-stability": "alpha",
if you need alpha packages, put the @alpha on the package, don't allow all packages to be alpha

2022-09-12 08:30 UTC, andytson-inviqa requested changes
minumum-stability should remain stable

2022-10-30 06:47 UTC, andytson commented on src/wordpress/application/skeleton/composer.json.twig
> +        "phpcsstandards/phpcsutils": "1.0.0-alpha4",
https://packagist.org/packages/phpcsstandards/phpcsdevtools#1.0.0 there's a release out now

2022-10-30 06:48 UTC, kierenevans commented on src/wordpress/application/skeleton/composer.json.twig
> +        "phpcsstandards/phpcsutils": "1.0.0-alpha4",
Different package unfortunately :(

2022-11-09 09:55 UTC, andytson-inviqa submitted a review, later dismissed

2022-12-09 11:43 UTC, andytson-inviqa approved these changes, later dismissed

2022-12-09 12:03 UTC, andytson-inviqa commented
```
Root composer.json requires phpcompatibility/php-compatibility dev-develop@alpha, found phpcompatibility/php-compatibility[dev-develop, 10.x-dev (alias of dev-develop)] but it does not match your minimum-stability.
```
ugh, an evil to solve an lesser evil

2022-12-09 12:15 UTC, andytson-inviqa commented
Does it need `@alpha` for dev-develop?

2022-12-09 12:39 UTC, andytson-inviqa commented
possibly just a magento1 error now:

```
#11 54.26 Your requirements could not be resolved to an installable set of packages.
#11 54.26 
#11 54.26   Problem 1
#11 54.26     - Root composer.json requires phpcompatibility/php-compatibility dev-develop -> satisfiable by phpcompatibility/php-compatibility[dev-develop].
#11 54.26     - phpcompatibility/php-compatibility dev-develop requires squizlabs/php_codesniffer ^3.7.1 -> found squizlabs/php_codesniffer[3.7.1] but it conflicts with your root composer.json require (3.2.2).
#11 54.26   Problem 2
#11 54.26     - Root composer.json requires phpcsstandards/phpcsutils 1.0.0-alpha4 -> satisfiable by phpcsstandards/phpcsutils[1.0.0-alpha4].
#11 54.26     - phpcsstandards/phpcsutils 1.0.0-alpha4 requires squizlabs/php_codesniffer ^3.7.1 || 4.0.x-dev@dev -> found squizlabs/php_codesniffer[3.7.1] but it conflicts with your root composer.json require (3.2.2).
```

2022-12-09 14:50 UTC, andytson-inviqa approved these changes

2022-12-09 14:50 UTC, merged