Destroy environment after quality tests
inviqa/harness-base-php pull request #768
Opened 2023-04-17 13:56 UTC by g-foster2

Ensure console container is rebuilt after having dev dependencies installed for quality tests.

2023-04-17 14:04 UTC, andytson-inviqa commented on test
> +function destroy_environment()
can we go for something a lot less impactful, like
```
docker-compose rm --stop console
```

2023-04-17 14:04 UTC, andytson-inviqa commented on test
> +function destroy_environment()
that way the console container doesn't need rebuilding or in mutagen's case a full resync of the volume

2023-04-17 14:06 UTC, andytson-inviqa commented on test
> +function destroy_environment()
however... acceptance tests also need the dev dependencies, so I'm not sure this is the answer

2023-04-17 14:07 UTC, andytson-inviqa requested changes
destroy is too destructive and acceptance tests need dev dependencies

2023-04-18 09:00 UTC, g-foster2020 commented
> destroy is too destructive and acceptance tests need dev dependencies

I can't see how the acceptance tests can require the dev dependencies because this works?

2023-04-18 09:01 UTC, andytson-inviqa commented
there's something more to it then, as obviously `behat` and co are dev dependencies and so would exist in console container

2023-04-18 09:04 UTC, andytson-inviqa commented on test
> +    docker-compose rm --stop console
this is missing `docker-compose up -d console` from my previous suggestion, so would probably force a rebuild of console still?

2023-04-18 09:05 UTC, andytson-inviqa commented
you're missing a harness label so no harnesses were tested

2023-04-18 09:05 UTC, g-foster2020 commented
Yes I can see run_project_quality_tests gets run twice. Before ws install and then during the acceptance tests. The issue was having it run before without cleaning up.

2023-04-18 09:10 UTC, g-foster2 commented
> Yes I can see run_project_quality_tests gets run twice. Before ws install and then during the acceptance tests. The issue was having it run before without cleaning up.

sorry ignore this ... run for magento only during acceptance tests

2023-04-18 09:14 UTC, g-foster2 commented
This does seem to be the wrong solution.

The issue is that ws install didn't fail when it should have done, because the quality tests were run first and they installed dev dependencies which hid an issue.

I think it would be better to either remove the dev dependencies after they are needed or have a clean environment before running install_environment.

2023-04-18 09:15 UTC, andytson-inviqa commented on test
> +    docker-compose rm --stop console
i.e. you only want to clear the changes to the console container based on what you're doing, so a rm and an up gets it to that state

2023-04-18 09:18 UTC, andytson-inviqa commented
Also the other thing is that project Jenkinsfile also has the dev dependencies installed behaviour. The test.sh is recreating those Jenkinsfiles steps in bash

2023-04-18 09:20 UTC, g-foster2 commented
It would be clearer to revert these changes and have a specific test_harness_install step.

2023-04-18 09:49 UTC, g-foster2 commented
This was a misguided solution due to lack of experience with the test script. PR will be closed and an issue opened for future consideration.

2023-04-18 09:49 UTC, closed without merging