Issue-57: root to own app data
inviqa/harness-base-php pull request #96
Opened 2019-05-22 13:46 UTC by marcomc

added a fix_app_permissions.sh.twig script/template to allow application user ownership and permissions to specific files and directory of the application while the rest of app files are owned by `root`

2019-05-22 18:45 UTC, kierenevans requested changes
Made some suggestions :)

2019-05-22 18:45 UTC, kierenevans commented on README.md
> +2. Clone https://github.com/inviqa/<framework>-sample in a test directory
These are private repos so only relevant to Inviqa employees.

Is there a better way to test this for a member of the public?

Wonder if this works, with `test/` being in `.gitignore` to allow for this:
```
./build
cd test
ws create drupal8-test inviqa/drupal8 --no-install
cp -pR ../dist/harness-drupal8/ drupal8-test/.my127ws/
cd drupal8-test/
ws install
```

2019-05-22 18:45 UTC, kierenevans commented on src/_base/harness/config/confd.yml
> +  - { src: docker/image/php-fpm/root/fix_app_permissions.sh}
```suggestion
  - { src: docker/image/php-fpm/root/fix_app_permissions.sh }
```

2019-05-22 18:45 UTC, kierenevans commented on src/drupal8/harness/config/confd.yml
> +  - { src: docker/image/php-fpm/root/fix_app_permissions.sh}
```suggestion
  - { src: docker/image/php-fpm/root/fix_app_permissions.sh }
```

2019-05-22 18:45 UTC, kierenevans commented on src/magento1/harness.yml
> +      - '/app/public/app/etc/local.xml'
Bit strange to have this writeable by magento - https://github.com/continuouspipe/dockerfiles/blob/1e63f8532ec7a6adab4d474987f70540fd2a1271/magento1/usr/local/share/magento1/magento_functions.sh#L16 isn't doing that so perhaps remove this line.
```suggestion
```

2019-05-22 18:45 UTC, kierenevans commented on src/magento1/harness/config/confd.yml
> +  - { src: docker/image/php-fpm/root/fix_app_permissions.sh}
```suggestion
  - { src: docker/image/php-fpm/root/fix_app_permissions.sh }
```

2019-05-22 18:45 UTC, kierenevans commented on src/magento2/harness/config/confd.yml
> +  - { src: docker/image/php-fpm/root/fix_app_permissions.sh}
```suggestion
  - { src: docker/image/php-fpm/root/fix_app_permissions.sh }
```

2019-05-22 18:45 UTC, kierenevans commented on src/spryker/harness/config/confd.yml
> +  - { src: docker/image/php-fpm/root/fix_app_permissions.sh}
```suggestion
  - { src: docker/image/php-fpm/root/fix_app_permissions.sh }
```

2019-05-22 18:45 UTC, kierenevans commented on src/drupal8/harness.yml
> +      - '/app/config'
Also need these: https://github.com/continuouspipe/dockerfiles/blob/3fb53b51bd3b04dbc15855e9f6601fa7fa3cba76/drupal/usr/local/share/drupal/drupal_functions.sh#L39-L40

2019-05-24 18:05 UTC, marcomc commented on README.md
> +2. Clone https://github.com/inviqa/<framework>-sample in a test directory
althought theyt in the dist/application/skeleton
the privisioning reports:
```
fixed permissions for /app/config
/docroot/modules does not exist
/docroot/profiles does not exist
/docroot/sites/default/files does not exist
```

2019-05-24 18:21 UTC, kierenevans commented on README.md
> +2. Clone https://github.com/inviqa/<framework>-sample in a test directory
I think we should make the directories if they don't exist (same for all frameworks).

2019-05-30 04:00 UTC, marcomc commented on README.md
> +2. Clone https://github.com/inviqa/<framework>-sample in a test directory
I have updated the script to create the missing files and dirs.
I have updated the instructions to create tests environment without using private company repos

2019-05-30 06:44 UTC, kierenevans commented
Wordpress's static build in Jenkins is complaining that:
```
■ > docker build -t blog:develop-php-fpm .
Sending build context to Docker daemon  16.38kB
Step 1/7 : FROM blog:develop-console as console
 ---> 07d3fa7b785c
Step 2/7 : FROM my127/wordpress:7.2-fpm-stretch
 ---> e945a53da66c
Step 3/7 : WORKDIR /app
 ---> Running in f200c9c69bbd
Removing intermediate container f200c9c69bbd
 ---> efaa056caaf7
Step 4/7 : COPY root  /
 ---> d609b574bcd7
Step 5/7 : COPY --from=console --chown=root:root /app /app
 ---> dc19151f44a9
Step 6/7 : RUN bash /fix_app_permissions.sh
 ---> Running in 88fd05f3aa53
bash: /fix_app_permissions.sh: No such file or directory
```

I think we need to have an entry present for all framework's confd.yml to avoid that.

2019-05-30 06:49 UTC, kierenevans commented
We should probably get some defaults going in `src/_base/harness/attributes/common.yml`, e.g.:
```
 app:
    owner: www-data
    group: www-data
    dirs: []
    files: []
```

2019-05-30 06:49 UTC, kierenevans requested changes
Almost there - just the wordpress static build's failure and some more suggestions.

2019-05-30 06:49 UTC, kierenevans commented on README.md
> +cp -pR ../dist/harness-<framework>/ <framework>/.my127ws/
```suggestion
cp -pR ../dist/harness-<framework>/ <framework>-test/.my127ws/
```

2019-05-30 06:49 UTC, kierenevans commented on src/drupal8/.ci/sample-static/workspace.yml
> +key('default'): ebbff2496560c9ada246d3783065998cd3799ccabd59c80b7257725218b01095
```suggestion
```

2019-05-30 06:49 UTC, kierenevans commented on src/drupal8/harness.yml
> +      - '/docroot/modules'
```suggestion
      - '/app/docroot/modules'
```

2019-05-30 06:49 UTC, kierenevans commented on src/drupal8/harness.yml
> +      - '/docroot/profiles'
```suggestion
      - '/app/docroot/profiles'
```

2019-05-30 06:49 UTC, kierenevans commented on src/drupal8/harness.yml
> +      - '/docroot/sites/default/files'
```suggestion
      - '/app/docroot/sites/default/files'
```

2019-05-30 06:49 UTC, kierenevans commented on README.md
> +2. create and cd a tests directory
```suggestion
2. create and change to a tests directory
```

2019-05-30 16:27 UTC, marcomc commented
> Wordpress's static build in Jenkins is complaining that:
> 
> ```
> ■ > docker build -t blog:develop-php-fpm .
> Sending build context to Docker daemon  16.38kB
> Step 1/7 : FROM blog:develop-console as console
>  ---> 07d3fa7b785c
> Step 2/7 : FROM my127/wordpress:7.2-fpm-stretch
>  ---> e945a53da66c
> Step 3/7 : WORKDIR /app
>  ---> Running in f200c9c69bbd
> Removing intermediate container f200c9c69bbd
>  ---> efaa056caaf7
> Step 4/7 : COPY root  /
>  ---> d609b574bcd7
> Step 5/7 : COPY --from=console --chown=root:root /app /app
>  ---> dc19151f44a9
> Step 6/7 : RUN bash /fix_app_permissions.sh
>  ---> Running in 88fd05f3aa53
> bash: /fix_app_permissions.sh: No such file or directory
> ```
> 
> I think we need to have an entry present for all framework's confd.yml to avoid that.

done

2019-05-30 16:29 UTC, marcomc commented
> We should probably get some defaults going in `src/_base/harness/attributes/common.yml`, e.g.:
> 
> ```
>  app:
>     owner: www-data
>     group: www-data
>     dirs: []
>     files: []
> ```
> 
> I guess these could also be more obvious, e.g. app.web_writable_dirs and app.web_writable_files ?

renamed all the attributes to 
```
web_owner
web_group
web_writable_dirs
web_writable_files
```

2019-05-30 16:30 UTC, marcomc commented
> Made some suggestions :)

good suggestions. I have applied them all. Thank you.

2019-05-31 06:26 UTC, kierenevans approved these changes
Great stuff! :tada:

2019-05-31 06:26 UTC, merged